# -*- coding: utf-8 -*-
{
    'name': 'Employee 360 Dashboard ',
    'version': '19.0.1.0.1',
    'summary': 'Field-force management: visits, PJP, beat, KPI — Odoo 19 Enterprise',
    'category': 'Human Resources',
    'author': 'Senior Odoo Developer',
    'license': 'OPL-1',
    'depends': [
        'hr',
        'hr_attendance',
        'hr_timesheet',
        'hr_expense',
        'beat_module_v19',
        'sale_management',
        'account',
        'mail',
        'web',
        'uom_conversion_hub',
        'uom',
        'product',
        'schemes_promotions_v19',
    ],
    'data': [
        'security/security.xml',
        'data/visit_sequence.xml',
        'security/ir.model.access.csv',
        'data/territory_data.xml',
        'views/pjp_generate_wizard_views.xml',
        'views/pjp_model_views.xml',
        'views/account_partner_views.xml',
        'views/territory_views.xml',
        'views/holiday_views.xml',
        'views/main_menu.xml',
        'views/employee_client_action_views.xml',
        'views/visit_views.xml',
        'views/executive_beat_report_views.xml',
        'views/dashboard_reports.xml',
        'views/dashboard_report_view.xml',
        'views/uom_master_views.xml',
        'views/main_menu_actions.xml',
        'views/product_category_views.xml',
        'views/price_book_views.xml',
        # 'views/product_hub_views.xml',
        'views/beat_extension_views.xml',
        'views/hr_employee.xml',
        'views/hr_attendance.xml',
        'views/sfa_expense_band_views.xml',
        'views/sale_order.xml',
        'views/visit_stock_views.xml',
        'views/visit_collection_views.xml',
        'views/visit_ticket_views.xml',
        'views/visit_competitor_views.xml',
        'views/visit_checklist_views.xml',
        'views/visit_geofence_views.xml',
        'views/asset_management_views.xml',
        'data/price_book_priority_data.xml',
        # 'views/territory_views.xml',
        # 'views/main_menu.xml',
        # 'views/main_menu_actions.xml',
        # 'views/employee_client_action_views.xml',
        # 'views/product_category_views.xml',
        # 'views/uom_master_views.xml',
        # 'views/price_book_views.xml',
        # # 'views/product_hub_views.xml',
        # 'views/account_partner_views.xml',
        # 'views/hr_employee.xml',
        # 'views/hr_attendance.xml',
        # 'views/visit_views.xml',
        # 'views/pjp_model_views.xml',
        # 'views/pjp_generate_wizard_views.xml',
        # 'views/executive_beat_report_views.xml',
        # 'views/dashboard_reports.xml',
        # 'views/dashboard_report_view.xml',
        # 'views/sale_order.xml',
        # 'views/visit_stock_views.xml',
        # 'views/visit_collection_views.xml',
        # 'views/visit_ticket_views.xml',
        # 'views/visit_competitor_views.xml',
        # 'views/visit_checklist_views.xml',
        # 'views/visit_geofence_views.xml',
        # 'views/asset_management_views.xml',
        # 'data/price_book_priority_data.xml',
        
    ],
    'assets': {
        'web.assets_backend': [
            'employee_dashboard_v19/static/lib/chart.min.js',
            'employee_dashboard_v19/static/lib/fullcalendar/main.min.css',
            'employee_dashboard_v19/static/lib/fullcalendar/main.min.js',
            'employee_dashboard_v19/static/lib/leaflet/leaflet.css',
            'employee_dashboard_v19/static/lib/leaflet/leaflet.js',
            'employee_dashboard_v19/static/src/css/style.css',
            'employee_dashboard_v19/static/src/component/js/**',
            'employee_dashboard_v19/static/src/component/xml/**',
        ],
    },
    'installable': True,
    'application': False,
    'auto_install': False,
}
