{
    'name': 'SFA Incentive Manager',
    'version': '19.0.1.0.0',
    'summary': 'Incentive Slab Manager and Calculation Dashboard',
    'category': 'Sales',
    'author': 'Fingertip',
    'depends': ['base', 'hr', 'mail', 'web', 'employee_dashboard_v19', 'kpi_target_v19'],
    'data': [
        'security/ir.model.access.csv',
        'data/target_criteria_data.xml',
        'views/target_criteria_views.xml',
        'views/target_allocation_views.xml',
        'views/incentive_profile_views.xml',
        'views/incentive_slab_views.xml',
        'views/incentive_record_views.xml',
        'views/menus.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'sfa_incentive/static/src/css/incentive_dashboard.css',
            'sfa_incentive/static/src/js/incentive_dashboard.js',
            'sfa_incentive/static/src/xml/incentive_dashboard.xml',
            'sfa_incentive/static/src/js/slab_manager.js',
            'sfa_incentive/static/src/xml/slab_manager.xml',
            'sfa_incentive/static/src/css/target_criteria_manager.css',
            'sfa_incentive/static/src/js/target_criteria_manager.js',
            'sfa_incentive/static/src/xml/target_criteria_manager.xml',
            'sfa_incentive/static/src/css/target_allocation.css',
            'sfa_incentive/static/src/js/target_allocation.js',
            'sfa_incentive/static/src/xml/target_allocation.xml',
            'sfa_incentive/static/src/css/kpi_dashboard.css',
            'sfa_incentive/static/src/js/kpi_dashboard.js',
            'sfa_incentive/static/src/xml/kpi_dashboard.xml',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
